version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    depends_on:
      - couchbase
    environment:
      - COUCHBASE_HOST=couchbase
      - COUCHBASE_PORT=27017

  couchbase:
    image: couchbase:latest
    # container_name: couchbase
    # ports:
    #   - "27017:27017"
          